// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: a.proto

package a

import (
	context "context"
	basemsg "github.com/vanh01/grpc-base/protos/basemsg"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	A_SendMessage_FullMethodName = "/a.A/SendMessage"
)

// AClient is the client API for A service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AClient interface {
	SendMessage(ctx context.Context, in *basemsg.GEventMessage, opts ...grpc.CallOption) (*basemsg.GEventResult, error)
}

type aClient struct {
	cc grpc.ClientConnInterface
}

func NewAClient(cc grpc.ClientConnInterface) AClient {
	return &aClient{cc}
}

func (c *aClient) SendMessage(ctx context.Context, in *basemsg.GEventMessage, opts ...grpc.CallOption) (*basemsg.GEventResult, error) {
	out := new(basemsg.GEventResult)
	err := c.cc.Invoke(ctx, A_SendMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AServer is the server API for A service.
// All implementations must embed UnimplementedAServer
// for forward compatibility
type AServer interface {
	SendMessage(context.Context, *basemsg.GEventMessage) (*basemsg.GEventResult, error)
	mustEmbedUnimplementedAServer()
}

// UnimplementedAServer must be embedded to have forward compatible implementations.
type UnimplementedAServer struct {
}

func (UnimplementedAServer) SendMessage(context.Context, *basemsg.GEventMessage) (*basemsg.GEventResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedAServer) mustEmbedUnimplementedAServer() {}

// UnsafeAServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AServer will
// result in compilation errors.
type UnsafeAServer interface {
	mustEmbedUnimplementedAServer()
}

func RegisterAServer(s grpc.ServiceRegistrar, srv AServer) {
	s.RegisterService(&A_ServiceDesc, srv)
}

func _A_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(basemsg.GEventMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: A_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AServer).SendMessage(ctx, req.(*basemsg.GEventMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// A_ServiceDesc is the grpc.ServiceDesc for A service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var A_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "a.A",
	HandlerType: (*AServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _A_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "a.proto",
}
