// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: base_msg.proto

package basemsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GEventMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data           string `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	DataType       string `protobuf:"bytes,2,opt,name=DataType,proto3" json:"DataType,omitempty"`
	ReturnDataType string `protobuf:"bytes,3,opt,name=ReturnDataType,proto3" json:"ReturnDataType,omitempty"`
	ConsumerType   string `protobuf:"bytes,4,opt,name=ConsumerType,proto3" json:"ConsumerType,omitempty"`
}

func (x *GEventMessage) Reset() {
	*x = GEventMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GEventMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GEventMessage) ProtoMessage() {}

func (x *GEventMessage) ProtoReflect() protoreflect.Message {
	mi := &file_base_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GEventMessage.ProtoReflect.Descriptor instead.
func (*GEventMessage) Descriptor() ([]byte, []int) {
	return file_base_msg_proto_rawDescGZIP(), []int{0}
}

func (x *GEventMessage) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *GEventMessage) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *GEventMessage) GetReturnDataType() string {
	if x != nil {
		return x.ReturnDataType
	}
	return ""
}

func (x *GEventMessage) GetConsumerType() string {
	if x != nil {
		return x.ConsumerType
	}
	return ""
}

type GEventResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data     string `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	DataType string `protobuf:"bytes,2,opt,name=DataType,proto3" json:"DataType,omitempty"`
}

func (x *GEventResult) Reset() {
	*x = GEventResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GEventResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GEventResult) ProtoMessage() {}

func (x *GEventResult) ProtoReflect() protoreflect.Message {
	mi := &file_base_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GEventResult.ProtoReflect.Descriptor instead.
func (*GEventResult) Descriptor() ([]byte, []int) {
	return file_base_msg_proto_rawDescGZIP(), []int{1}
}

func (x *GEventResult) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *GEventResult) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

var File_base_msg_proto protoreflect.FileDescriptor

var file_base_msg_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x62, 0x61, 0x73, 0x65, 0x6d, 0x73, 0x67, 0x22, 0x8b, 0x01, 0x0a, 0x0d, 0x47, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x1a, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x52,
	0x65, 0x74, 0x75, 0x72, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x43, 0x6f, 0x6e, 0x73, 0x75,
	0x6d, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x22, 0x3e, 0x0a, 0x0c, 0x47, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x44,
	0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x44,
	0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x61, 0x6e, 0x68, 0x30, 0x31, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x2d, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x62, 0x61,
	0x73, 0x65, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_base_msg_proto_rawDescOnce sync.Once
	file_base_msg_proto_rawDescData = file_base_msg_proto_rawDesc
)

func file_base_msg_proto_rawDescGZIP() []byte {
	file_base_msg_proto_rawDescOnce.Do(func() {
		file_base_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_base_msg_proto_rawDescData)
	})
	return file_base_msg_proto_rawDescData
}

var file_base_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_base_msg_proto_goTypes = []interface{}{
	(*GEventMessage)(nil), // 0: basemsg.GEventMessage
	(*GEventResult)(nil),  // 1: basemsg.GEventResult
}
var file_base_msg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_base_msg_proto_init() }
func file_base_msg_proto_init() {
	if File_base_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_base_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GEventMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_base_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GEventResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_base_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_base_msg_proto_goTypes,
		DependencyIndexes: file_base_msg_proto_depIdxs,
		MessageInfos:      file_base_msg_proto_msgTypes,
	}.Build()
	File_base_msg_proto = out.File
	file_base_msg_proto_rawDesc = nil
	file_base_msg_proto_goTypes = nil
	file_base_msg_proto_depIdxs = nil
}
