// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: b.proto

package b

import (
	context "context"
	basemsg "github.com/vanh01/grpc-base/protos/basemsg"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	B_SendMessage_FullMethodName = "/b.B/SendMessage"
)

// BClient is the client API for B service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BClient interface {
	SendMessage(ctx context.Context, in *basemsg.GEventMessage, opts ...grpc.CallOption) (*basemsg.GEventResult, error)
}

type bClient struct {
	cc grpc.ClientConnInterface
}

func NewBClient(cc grpc.ClientConnInterface) BClient {
	return &bClient{cc}
}

func (c *bClient) SendMessage(ctx context.Context, in *basemsg.GEventMessage, opts ...grpc.CallOption) (*basemsg.GEventResult, error) {
	out := new(basemsg.GEventResult)
	err := c.cc.Invoke(ctx, B_SendMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BServer is the server API for B service.
// All implementations must embed UnimplementedBServer
// for forward compatibility
type BServer interface {
	SendMessage(context.Context, *basemsg.GEventMessage) (*basemsg.GEventResult, error)
	mustEmbedUnimplementedBServer()
}

// UnimplementedBServer must be embedded to have forward compatible implementations.
type UnimplementedBServer struct {
}

func (UnimplementedBServer) SendMessage(context.Context, *basemsg.GEventMessage) (*basemsg.GEventResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedBServer) mustEmbedUnimplementedBServer() {}

// UnsafeBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BServer will
// result in compilation errors.
type UnsafeBServer interface {
	mustEmbedUnimplementedBServer()
}

func RegisterBServer(s grpc.ServiceRegistrar, srv BServer) {
	s.RegisterService(&B_ServiceDesc, srv)
}

func _B_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(basemsg.GEventMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: B_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BServer).SendMessage(ctx, req.(*basemsg.GEventMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// B_ServiceDesc is the grpc.ServiceDesc for B service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var B_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "b.B",
	HandlerType: (*BServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _B_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "b.proto",
}
